import React, { useState, useEffect, useMemo } from 'react';
import { 
  Github, 
  ExternalLink, 
  Search, 
  Star, 
  GitFork, 
  BookOpen, 
  RefreshCw,
  Globe,
  Code2,
  Calendar
} from 'lucide-react';

const GITHUB_USERNAME = "YOUR_GITHUB_USERNAME"; // Replace this!
const DATA_FILE_URL = "./repos.json"; // The file generated by GitHub Actions
const CACHE_KEY = `gh_projects_${GITHUB_USERNAME}`;
const CACHE_EXPIRY = 3600000; // 1 hour in milliseconds

const App = () => {
  const [repos, setRepos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [dataSource, setDataSource] = useState("fetching");

  const fetchProjects = async () => {
    setLoading(true);
    
    // 1. Try LocalStorage Cache first for instant load
    const cached = localStorage.getItem(CACHE_KEY);
    if (cached) {
      const { data, timestamp } = JSON.parse(cached);
      if (Date.now() - timestamp < CACHE_EXPIRY) {
        setRepos(data);
        setLoading(false);
        setDataSource("cache");
        // Background revalidation
        revalidateData();
        return;
      }
    }

    // 2. Try the Static File (Generated by GitHub Actions)
    try {
      const response = await fetch(DATA_FILE_URL);
      if (response.ok) {
        const data = await response.json();
        updateStateAndCache(data, "static-file");
        return;
      }
    } catch (e) {
      console.log("Static file not found, falling back to API...");
    }

    // 3. Fallback to Live API (Subject to Rate Limits)
    revalidateData();
  };

  const revalidateData = async () => {
    try {
      const response = await fetch(`https://api.github.com/users/${GITHUB_USERNAME}/repos?sort=updated&per_page=100`);
      if (!response.ok) throw new Error(`GitHub API Error: ${response.status}`);
      const data = await response.json();
      updateStateAndCache(data, "api");
    } catch (err) {
      setError(err.message);
      setLoading(false);
    }
  };

  const updateStateAndCache = (data, source) => {
    const formattedData = data
      .filter(repo => !repo.fork) // Usually better for portfolios
      .map(repo => ({
        id: repo.id,
        name: repo.name,
        description: repo.description,
        stars: repo.stargazers_count,
        forks: repo.forks_count,
        language: repo.language,
        html_url: repo.html_url,
        homepage: repo.homepage || (repo.has_pages ? `https://${GITHUB_USERNAME}.github.io/${repo.name}/` : null),
        updated_at: repo.updated_at,
        topics: repo.topics || []
      }));

    setRepos(formattedData);
    setDataSource(source);
    setLoading(false);
    localStorage.setItem(CACHE_KEY, JSON.stringify({
      data: formattedData,
      timestamp: Date.now()
    }));
  };

  useEffect(() => {
    fetchProjects();
  }, []);

  const filteredRepos = useMemo(() => {
    return repos.filter(repo => 
      repo.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (repo.description && repo.description.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (repo.language && repo.language.toLowerCase().includes(searchQuery.toLowerCase()))
    );
  }, [repos, searchQuery]);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans selection:bg-blue-100">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-white/80 backdrop-blur-md border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-6 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-slate-900 rounded-lg text-white">
              <Github size={24} />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight">{GITHUB_USERNAME}</h1>
              <p className="text-xs text-slate-500 flex items-center gap-1">
                <RefreshCw size={10} className={loading ? "animate-spin" : ""} />
                Data source: <span className="font-medium text-slate-700 uppercase tracking-widest text-[9px]">{dataSource}</span>
              </p>
            </div>
          </div>

          <div className="relative group flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 transition-colors group-focus-within:text-blue-500" size={18} />
            <input 
              type="text"
              placeholder="Search projects or languages..."
              className="w-full pl-10 pr-4 py-2 bg-slate-100 border-none rounded-full text-sm focus:ring-2 focus:ring-blue-500/20 focus:bg-white transition-all outline-none"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-12">
        {loading && repos.length === 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="h-48 bg-white rounded-2xl border border-slate-200 animate-pulse shadow-sm" />
            ))}
          </div>
        ) : error && repos.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-3xl border border-dashed border-slate-300">
            <div className="text-red-500 mb-4 inline-block p-4 bg-red-50 rounded-full">
              <Globe size={48} />
            </div>
            <h2 className="text-xl font-semibold mb-2">Connection Issue</h2>
            <p className="text-slate-500 max-w-sm mx-auto mb-6">{error}</p>
            <button 
              onClick={revalidateData}
              className="px-6 py-2 bg-slate-900 text-white rounded-full text-sm font-medium hover:bg-slate-800 transition-colors"
            >
              Try Again
            </button>
          </div>
        ) : (
          <>
            <div className="mb-8 flex items-center justify-between">
              <h2 className="text-2xl font-bold flex items-center gap-2">
                All Projects
                <span className="text-sm font-normal text-slate-400 bg-slate-100 px-2 py-0.5 rounded-md">
                  {filteredRepos.length}
                </span>
              </h2>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredRepos.map((repo) => (
                <div 
                  key={repo.id}
                  className="group flex flex-col bg-white border border-slate-200 rounded-2xl p-6 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
                >
                  <div className="flex justify-between items-start mb-4">
                    <div className="p-2 bg-blue-50 text-blue-600 rounded-lg group-hover:bg-blue-600 group-hover:text-white transition-colors">
                      <BookOpen size={20} />
                    </div>
                    <div className="flex gap-3">
                      <a 
                        href={repo.html_url} 
                        target="_blank" 
                        rel="noreferrer"
                        className="text-slate-400 hover:text-slate-900 transition-colors"
                        title="View Source"
                      >
                        <Code2 size={18} />
                      </a>
                      {repo.homepage && (
                        <a 
                          href={repo.homepage} 
                          target="_blank" 
                          rel="noreferrer"
                          className="text-slate-400 hover:text-green-600 transition-colors"
                          title="Live Demo"
                        >
                          <ExternalLink size={18} />
                        </a>
                      )}
                    </div>
                  </div>

                  <h3 className="text-lg font-bold mb-2 group-hover:text-blue-600 transition-colors truncate">
                    {repo.name.replace(/-/g, ' ')}
                  </h3>
                  
                  <p className="text-slate-500 text-sm line-clamp-2 mb-6 flex-grow">
                    {repo.description || "No description provided."}
                  </p>

                  <div className="flex flex-wrap gap-2 mb-6">
                    {repo.topics.slice(0, 3).map(topic => (
                      <span key={topic} className="text-[10px] font-bold uppercase tracking-wider text-slate-400 bg-slate-50 px-2 py-1 rounded">
                        {topic}
                      </span>
                    ))}
                  </div>

                  <div className="pt-4 border-t border-slate-100 flex items-center justify-between text-xs font-medium text-slate-400">
                    <div className="flex items-center gap-4">
                      <span className="flex items-center gap-1">
                        <Star size={12} className="text-amber-400" /> {repo.stars}
                      </span>
                      <span className="flex items-center gap-1">
                        <GitFork size={12} /> {repo.forks}
                      </span>
                    </div>
                    <div className="flex items-center gap-1">
                      <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                      {repo.language || "Plain"}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {filteredRepos.length === 0 && (
              <div className="text-center py-20 bg-white rounded-3xl border border-slate-200">
                <p className="text-slate-400">No repositories found matching "{searchQuery}"</p>
              </div>
            )}
          </>
        )}
      </main>

      <footer className="max-w-6xl mx-auto px-6 py-12 border-t border-slate-200 flex flex-col md:flex-row justify-between items-center gap-4 text-slate-400 text-sm">
        <p>© {new Date().getFullYear()} {GITHUB_USERNAME}. All code open source.</p>
        <div className="flex items-center gap-4">
          <a href={`https://github.com/${GITHUB_USERNAME}`} className="hover:text-slate-900 transition-colors">GitHub</a>
          <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
          <a href="#" className="hover:text-slate-900 transition-colors">Portfolio</a>
        </div>
      </footer>
    </div>
  );
};

export default App;